-- FIRST IMPORT THE DATA

CREATE TABLE USED_CARS
(
	MODEL_NAME VARCHAR(70),
	PRICE FLOAT,
	MANUFACTURING_YEAR INT,
	ENGINE_CAPACITY INT,
	SPARE_KEY BOOLEAN,
	TRANSMISSION VARCHAR(15),
	KM_DRIVEN INT,
	OWNERSHIP INT,
	FUEL_TYPE VARCHAR(10),
	IMPERFECTIONS INT,
	REPAINTED_PARTS INT 
)

-- GO TO USED_CARS AND IMPORT DATA FROM THE SPECIFIC LOCATION ON THE SYSTEM

-- DIMENSIONS [MODEL_NAME,MANUFACTURING_YEAR,ENGINE_CAPACITY,SPARE_KEY,TRANSMISSION,OWNERSHIP,FUEL_TYPE]
-- MEASURE [PRICE,KM_DRIVEN,IMPERFECTIONS,REPAINTED_PARTS]

-- LET'S SEE THE BROADER SECOND HAND CAR DATA OVER THE YEARS 

SELECT MANUFACTURING_YEAR ,SUM(PRICE) AS TOTAL_SALES ,COUNT(*) AS QUANTITY, 2024-MANUFACTURING_YEAR AS CAR_AGE
FROM USED_CARS
GROUP BY MANUFACTURING_YEAR
ORDER BY MANUFACTURING_YEAR;

-- MOST CARS ARE 7 YEARS OLDER
-- WE SEE A SPIKE IN NUMBER OF CARS SOLD WHICH ARE 10 YEARS OLDER


-- THE CARS THAT HAVE BEEN DRIVEN FOR 30K-40K HAS THE HIGHEST NUMBER OF SALES CORRESPONDING TO 6yrs TO 2YRS OLD CARS
SELECT KM_DRIVEN_RANGE ,SUM(PRICE) AS TOTAL_SALES ,COUNT(*) AS QUANTITY
FROM USED_CARS
GROUP BY KM_DRIVEN_RANGE
ORDER BY KM_DRIVEN_RANGE;


-- LET'S CREATE A NEW COLUMN KM DRIVEN IN A YEAR
ALTER TABLE USED_CARS
ADD COLUMN KM_PER_YEAR FLOAT;

-- LET'S SET IT'S VALUE
UPDATE USED_CARS
SET KM_PER_YEAR = (KM_DRIVEN_RANGE/(2024-MANUFACTURING_YEAR))*1000;

SELECT KM_PER_YEAR, ROUND(AVG(PRICE)::NUMERIC,2) AS PRICE ,COUNT(*)
FROM USED_CARS
-- WHERE CAR_NAME='WAGONR'
GROUP BY KM_PER_YEAR
ORDER BY KM_PER_YEAR;

-- THE PRICES WITH KM_PER_YEAR DOESN'T VARY MUCH BUT THE NUMBER OF CARS WITH 10000 KM/YEAR ARE THE MAXIMUM'
-- SINCE NO SIGNIFICANT ANALYSIS CAN BE MADE SO LETS DROP THIS COLUMN

ALTER TABLE USED_CARS
DROP COLUMN KM_PER_YEAR;


-- THE MODEL NAME IS VERY BROAD SO LET'S NARROW DOWN THE CATEGORY

ALTER TABLE USED_CARS
ADD COLUMN CAR_NAME VARCHAR(20); 

UPDATE USED_CARS
SET CAR_NAME = (
CASE 
WHEN MODEL_NAME ILIKE '%BALENO%' THEN 'BALENO'
WHEN MODEL_NAME ILIKE '%ERTIGA%' THEN 'ERTIGA'
WHEN MODEL_NAME ILIKE '%ALTO%' THEN 'ALTO'
WHEN MODEL_NAME ILIKE '%CELERIO%' THEN 'CELERIO'
WHEN MODEL_NAME ILIKE '%S%PRESSO%' THEN 'SPRESSO'
WHEN MODEL_NAME ILIKE '%WAGON%R%' THEN 'WAGONR'
WHEN MODEL_NAME ILIKE '%XL6%' THEN 'XL6'
WHEN MODEL_NAME ILIKE '%SWIFT%' THEN 'SWIFT'
WHEN MODEL_NAME ILIKE '%%DZIRE%' THEN 'SWIFT DZIRE'
WHEN MODEL_NAME ILIKE '%IGNIS%' THEN 'IGNIS'
WHEN MODEL_NAME ILIKE '%CIAZ%' THEN 'CIAZ'
WHEN MODEL_NAME ILIKE '%EECO%' THEN 'EECO'
WHEN MODEL_NAME ILIKE '%RITZ%' THEN 'RITZ'
WHEN MODEL_NAME ILIKE '%OMNI%' THEN 'OMNI'
WHEN MODEL_NAME ILIKE '%S%CROSS%' THEN 'SCROSS'
WHEN MODEL_NAME ILIKE '%VITARA%BREZZA%' THEN 'VITARA BREZZA'
WHEN MODEL_NAME ILIKE '%BREZZA%HYBRID%' THEN 'BREZZA HYBRID'
WHEN MODEL_NAME ILIKE '%GRAND%VITARA%' THEN 'GRAND VITARA'
END
)

-- LET'S SEE WHICH IS THE MOST SOLD CARS IN SECOND HAND CAR MARKET

SELECT CAR_NAME , COUNT(*) AS CAR_COUNT
FROM USED_CARS
GROUP BY CAR_NAME
ORDER BY CAR_COUNT DESC;

-- TOP FIVE ARE
"BALENO"	236
"WAGONR"	235
"SWIFT"		212
"ALTO"		161
"CELERIO"	141

-- BUT THIS CAN BE AFFECTED BY THEIR MAINUFACTURING YEARS
-- LET'S CALCULATE SOLD/YEAR

SELECT CAR_NAME , (COUNT(*)/(2024-MIN(MANUFACTURING_YEAR))) AS CAR_SOLD_PER_YEAR , COUNT(*) , MIN(MANUFACTURING_YEAR)
FROM USED_CARS
GROUP BY CAR_NAME
ORDER BY CAR_SOLD_PER_YEAR DESC;

-- NOW THE TOP 5 ARE

"BALENO"	26	
"WAGONR"	18	
"SWIFT"		16	
"CELERIO"	14	
"SPRESSO"	13	

-- NOW LET'S ALSO GROUP BY FUEL_TYPE 

WITH CarSales AS (
    SELECT 
        CAR_NAME, 
        COUNT(*) AS TOTAL_SOLD,
        MIN(MANUFACTURING_YEAR) AS FIRST_YEAR,
        (COUNT(*) * 1.0) / (2024 - MIN(MANUFACTURING_YEAR)) AS CAR_SOLD_PER_YEAR
    FROM USED_CARS
    GROUP BY CAR_NAME
),
Top5Cars AS (
    SELECT CAR_NAME 
    FROM CarSales
    ORDER BY CAR_SOLD_PER_YEAR DESC
    LIMIT 5
)
SELECT 
    UC.CAR_NAME,
    UC.FUEL_TYPE,
    COUNT(*) AS TOTAL_SOLD,
    MIN(UC.MANUFACTURING_YEAR) AS FIRST_YEAR,
    ROUND((COUNT(*) * 1.0) / (2024 - MIN(UC.MANUFACTURING_YEAR))) AS CAR_SOLD_PER_YEAR
FROM USED_CARS UC
WHERE UC.CAR_NAME IN (SELECT CAR_NAME FROM Top5Cars)
GROUP BY UC.CAR_NAME, UC.FUEL_TYPE
ORDER BY CAR_SOLD_PER_YEAR DESC;

-- THE DEMAND IS OF FIRST PETROL CARS, THEN CNG AND THEN DIESEL

-- LET'S DO SAME FOR TRANSMISSION

WITH CarSales AS (
    SELECT 
        CAR_NAME, 
        COUNT(*) AS TOTAL_SOLD,
        MIN(MANUFACTURING_YEAR) AS FIRST_YEAR,
        ROUND((COUNT(*) * 1.0) / (2024 - MIN(MANUFACTURING_YEAR))) AS CAR_SOLD_PER_YEAR
    FROM USED_CARS
    GROUP BY CAR_NAME
),
Top5Cars AS (
    SELECT CAR_NAME 
    FROM CarSales
    ORDER BY CAR_SOLD_PER_YEAR DESC
    LIMIT 5
)
SELECT 
    UC.CAR_NAME,
    UC.TRANSMISSION,
    COUNT(*) AS TOTAL_SOLD,
    MIN(UC.MANUFACTURING_YEAR) AS FIRST_YEAR,
    ROUND((COUNT(*) * 1.0) / (2024 - MIN(UC.MANUFACTURING_YEAR))) AS CAR_SOLD_PER_YEAR
FROM USED_CARS UC
WHERE UC.CAR_NAME IN (SELECT CAR_NAME FROM Top5Cars)
GROUP BY UC.CAR_NAME, UC.TRANSMISSION
ORDER BY CAR_SOLD_PER_YEAR DESC;

-- PREFERENCE IS OF MANUAL AND THEN AUTOMATIC
-- BALENO AUTOMATIC ALSO HAS SIGNIFICANT DEMAND WHICH MAY IMPLY THAT IT IS BOUGHT FOR PERSONAL USE

-- LET'S CHECK THE IMPACT OF REPAINTED PATS AND IMPERFECTIONS
SELECT REPAINTED_PARTS , ROUND(AVG(PRICE)::NUMERIC,2)
FROM USED_CARS
WHERE CAR_NAME = 'SWIFT'
GROUP BY REPAINTED_PARTS
ORDER BY REPAINTED_PARTS;

-- BOTH THE FACTORS HAVE VERY LITTLE EFFECT